### ISSUE TITLE
Date of birth verification by addhar number

### ISSUE THREAD

**Issue by blackcoder56** [ashwinbande/validators#2]
Hey sir, I want to make a website that can take Aadhar number and fetch date of birth of that person by addhar number and store it into database/(user enter Aadhar number and date of birth and it check that tha date of birth is correct or not by addhar number if correct than return true value)

**Comment by ashwinbande** [comment]
This is not an issue!
Please check if such API is available from UIDAI.

**Comment by blackcoder56** [comment]
Thank You Sir
